### ISSUE TITLE
API: disable/delete accounts

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/secretariat#306]
- [x] Github
- [x] Zammad
- [x] Sentry
- [x] OVH
- [x] Mattermost
- [x] Matomo
- [x] Nextcloud

**Comment by gary-van-woerkens** [comment]
Quel est le statut de chaque service finalement, peut-on tous les delete/disable ?
Quelles sont les subtilités ?

**Comment by Matmut7** [comment]
Je ferai une nouvelle issue pour le subtilités
