### ISSUE TITLE
Attention aux clefs APIs dans .socialgouv

### ISSUE THREAD

**Issue by gposbic** [SocialGouv/secretariat#322]
Bonjour,

Possible que ça soit une erreur mais les clefs API privées OVH, GITHUB, TIPIMAIL, NEXTCLOUD, etc. sont exposées dans **/.socialgouv/environments/prod**/. [Lien](https://github.com/SocialGouv/secretariat/tree/master/.socialgouv/environments/prod)]

Cdt,

**Comment by Matmut7** [comment]
Bonjour @gposbic,

Ces fichiers `sealed-secret` contiennent des valeurs chiffrées qui peuvent être déchiffrées seulement par le cluster Kubernetes sur lequel on déploie l'application. Plus d'infos sont disponibles sur leur repo : https://github.com/bitnami-labs/sealed-secrets

Merci pour votre retour :grin:
